-- AlterTable
ALTER TABLE "challenges" ALTER COLUMN "thresholds" SET DATA TYPE JSONB,
ALTER COLUMN "maxValue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "champions" ALTER COLUMN "hp" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hpPerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "mp" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "mpPerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "armor" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "armorPerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "spellBlock" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "spellBlockPerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attackRange" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hpRegen" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hpRegenPerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "mpRegen" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "mpRegenPerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "crit" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "critPerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attackDamage" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attackDamagePerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attackSpeed" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attackSpeedPerLevel" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "composition_suggestions" ADD COLUMN     "playstyle" TEXT,
ADD COLUMN     "strengths" TEXT,
ADD COLUMN     "weaknesses" TEXT,
ALTER COLUMN "confidence" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "discovered_players" ALTER COLUMN "lastCrawledAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "items" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "leaderboard_entries" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "league_accounts" ALTER COLUMN "winRate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avgKDA" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "match_participants" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "matches" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "ml_predictions" ALTER COLUMN "winProbability" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "ml_training_runs" ALTER COLUMN "startedAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "finishedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "player_challenges"
ALTER COLUMN "currentValue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "percentile" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "achievedTime" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "nextLevelValue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "progress" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pointsEarned" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "lastUpdatedByRiot" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "users" RENAME CONSTRAINT "new_users_pkey1" TO "users_pkey";

ALTER TABLE "users"
ALTER COLUMN "subscriptionExpiresAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "lastDailyReset" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);
